name: Deploy Payment Service


on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to HostingRaja
    runs-on: linux-latest

    steps:
 
      - name: Checkout Code
        uses: actions/checkout@v4


      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'


      - name: Install Dependencies
        run: npm install



      # 5️⃣ Deploy to HostingRaja via SSH
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOSTINGRAJA_HOST }}      # Your server IP
          username: ${{ secrets.HOSTINGRAJA_USER }}  # SSH username
          key: ${{ secrets.HOSTINGRAJA_SSH_KEY }}    # Private SSH key
          port: 22
          script: |
            cd /var/www/payment-service            # App folder on server
            git pull origin main
            npm install --production
            pm2 restart all || pm2 start npm --name "payment-service" -- run start
            echo "Payment Service deployed successfully!"
